Repository microsoft/code-with-engineering-playbook, pull requests merged in 2021-10, with the labels that each got.

#700 Updated setting environment variables
  docs/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/examples/commit-example.yaml
  docs/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/examples/pr-example.yaml
  docs/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/runtime-variables.md
Labels: CI/CD

#721 Bug/720 fix links argocd
  docs/design/design-reviews/decision-log/examples/memory/Trade-Studies/GitOps.md
Labels: design reviews

#716 detect-secrets example updates for Azure DevOps
  docs/continuous-integration/dev-sec-ops/secret-management/recipes/detect-secrets-ado.md
Labels: CI/CD

#672 Added README for Performance Testing as part of Automated Testing Content
  docs/automated-testing/performance-testing/README.md
Labels: testing

#719 Adding auto assigning of reviewers based on engineering fundamental
  .github/reviewers.yml
  .github/workflows/auto_request_review.yml
Labels: general

#729 exclude patterns for links that don't like bots
  .markdownlinkcheck.json
Labels: general
