Repository microsoft/code-with-engineering-playbook, pull requests merged in 2022-04, with the labels that each got.

#815 Fixed spelling and casing of "Azure DevOps"
  docs/code-reviews/recipes/go.md
  docs/continuous-integration/README.md
  docs/source-control/README.md
Labels: code reviews, CI/CD, source code

#810 ML Program Management guidance
  .markdownlinkcheck.json
  docs/machine-learning/images/ml-tpm-skills.png
  docs/machine-learning/ml-tpm-guidance.md
Labels: ml-fundamentals, Data Science

#814 Fixed casing of "GitHub"
  docs/code-reviews/inclusion-in-code-review.md
  docs/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/runtime-variables.md
  docs/developer-experience/going-further.md
  docs/observability/recipes-observability.md
Labels: code reviews, CI/CD, observability, source code

#822 added link to TPM guidance on ML readme
  docs/machine-learning/README.md
Labels: Data Science

#823 Fix mkdocs deployment bug
  Gemfile
  Gemfile.lock
  docs/code-reviews/pull-request-template/pull-request-template.md
  docs/machine-learning/responsible-ai.md
  requirements-docs.txt
Labels: general
