Repository microsoft/code-with-engineering-playbook, pull requests merged in 2022-02, with the labels that each got.

#788 updated markdown-link-check to address marked security issue
  package-lock.json
  package.json
Labels: dependabot

#794 updated cli to address #793
  CONTRIBUTING.md
  docs/continuous-delivery/README.md
  docs/engineering-feedback/feedback-guidance.md
  package-lock.json
  package.json
Labels: dependabot

#800 cleaned up CI content to address issue #479
  docs/continuous-integration/README.md
Labels: CI/CD

#727 Code review recommended practices
  CONTRIBUTING.md
  docs/code-reviews/process-guidance/README.md
  docs/code-reviews/process-guidance/author-guidance.md
  docs/code-reviews/process-guidance/reviewer-guidance.md
  docs/code-reviews/pull-requests.md
Labels: code reviews

#803 Shiranr/unify tools page
  docs/code-reviews/evidence-and-measures/README.md
  docs/code-reviews/evidence-and-measures/branch-policy.md
  docs/code-reviews/faq.md
  docs/code-reviews/process-guidance/README.md
  docs/code-reviews/process-guidance/author-guidance.md
  docs/code-reviews/process-guidance/customize-ado.md
  docs/code-reviews/tools.md
Labels: code reviews
