Repository microsoft/code-with-engineering-playbook, pull requests merged in 2022-08, with the labels that each got.

#866 Matt manuel/865 language mermaid update
  docs/documentation/tools/images/example-mermaid-diagram.mmd
  docs/documentation/tools/images/example-mermaid-diagram.png
  docs/documentation/tools/languages.md
Labels: design reviews

#874 Mount default ssh directory to dev container
  .devcontainer/devcontainer.json
Labels: bug

#872 Add best practices for mocking
  docs/automated-testing/unit-testing/README.md
  docs/automated-testing/unit-testing/mocking.md
Labels: testing
